const messages = {
  start: `<b>This bot will add 'iPhone-like' metadata, including GPS coordinates, to your content.</b>\n\n<b>Why?</b>\n<blockquote expandable><b>1. Target specific locations 🌍</b>\n\n<span class="tg-spoiler">By adding GPS coordinates, your account will be pushed harder in this location and other locations with a similar demographic. For example targeting other English-speaking or wealthy countries.</span></blockquote>\n<blockquote expandable><b>2. Bypass AI re-upload detection 🤖</b>\n\n<span class="tg-spoiler">Platforms use AI to detect re-uploaded content, but they start with metadata checks because it’s the fastest and cheapest method. Advanced image recognition requires significant computational resources, so if your metadata mimics genuine iPhone uploads, your content is far less likely to be flagged. Instead, it often gets overlooked, allowing it to bypass these checks. By adding convincing metadata, the platform is more likely to assume you’re the original creator and push your content further.</span></blockquote>\n<blockquote expandable><b>3. Algorithms favor authentic content ✅</b>\n\n<span class="tg-spoiler">Platforms prioritize content they perceive as genuine. Photos or videos with iPhone-like metadata appear authentic, which makes them more likely to be promoted by the algorithm. Authentic metadata signals to the platform that the content is original and worth pushing to more users.</span></blockquote>\n<blockquote expandable><b>4. Lower risk of account bans 🔒</b>\n\n<span class="tg-spoiler">When pushing content aggressively, there’s always a risk of being flagged as spam. Metadata that appears authentic makes your account look like it belongs to a real user rather than a bot. Platforms are less likely to flag or ban accounts with legitimate-looking metadata, giving you a safer way to grow your content reach.</span></blockquote>`,
  setLocation:
    "<b>🗺️ Send a location where you want the content to appear as taken from.</b>\n\nClick the 📎 icon and see 'location' in the bottom bar.\n\n<blockquote expandable><b>How adding location helps?</b>\n\n1. Posts are more likely to be pushed to people in that location.  You can target high income countries like USA, UAE etc.\n\n2. Your account is less likely to get banned as it's assumed you're posting raw content taken on an iPhone - not copied, AI etc. This gives your account more trust in the algorithm and it will be less likely to be flagged.</blockquote>",
  register:
    "We don't have you on the system yet. Please register by sending a location that you want your photos to appear as taken from.  Send a location by clicking the 📎 icon and selecting 'location' in the bottom bar.",
  registerSuccess: "<b>📍 LOCATION SET 📍</b>\n<blockquote>To change your location send a new location.</blockquote>",
  pay: "Ah it looks like you don't have a subscription.\n<i>Please choose an option:</i>",
  postTrialPitch:
    "<b>Benefits?</b>\n\nThe algorithms will have more trust in your account meaning:\n1. Pushing your content more to the location you set and places with similar demographics.\n2. Avoid the AI duplicate posts checks\n3. Reduce likelyhood of account bans\n4. Increase DM rate limits\n\n💡 Save the photo, do <b>not</b> screenshot if you want to keep metadata.\nTo verify the metadata check out exif.tools",
  subscriptionSuccess: "Successfully subscribed! You can now send as many photos as you like.",
  affiliate:
    "<b>Go to this bot's profile and join 'affiliate program' from there.</b>\n\n<i>You will get <b>27%</b> of the stars people spend through your link.</i>\n\n<blockquote expandable><b>How to withdraw Stars to cash?</b>\n\n<b>TLDR</b>\nWhen getting your affiliate link choose to send Stars commission to a channel you own and not your personal account.\n\n<b>1. Commission sent to your personal:</b>\nPersonal accounts cannot withdraw star balances, they can only spend stars within Telegram... option 2 however;\n\n2. <b>Commission sent to a channel you own:</b>\nChannels can withdraw to TON Crypto and from there to Local Currency.  So if you want to withdraw to the real world create a channel and set commission to go to this channel when when generating your affiliate link.<b>TLDR</b>\nWhen getting your affiliate link choose to send Stars commission to a channel you own and not your personal.\n\n🤫How to get stars ~35% cheaper through telegrams other company /fragment.</blockquote>",
  fragment: `<b>Get Telegram Stars ~30% off</b>\n\n1. Load up on some TON (Telegrams Crypto) using a wallet (the easiest to set up is <a href="https://tonkeeper.com/">TON Keeper</a> ~2min setup).\n\n2. Once you've got some TON in your wallet go to <a href="https://fragment.com/">Fragment</a> and buy Stars from there.\n\n<blockquote>This is because you're not buying through apple and androids App Stores which charges 30% per transaction.</blockquote>`,
  notSupported: "Ah! Photos must be sent as a file.\n<i>Tap the 📎 and select file from the bottom bar.</i>",
  report: `Message <a href="tg://user?id=7896600986">Jon</a> (Lead Developer) for any issues`,
};

export default messages;
