const messages = {
  start: `<b>😵‍💫This bot will add 'iPhone-like' metadata, including GPS coordinates, to your content.</b>\n\n<b>Why?</b>\n<blockquote expandable><b>1. Target specific locations 🌍</b>\n\n<span class="tg-spoiler">By adding GPS coordinates, you can control where your content gets promoted. Without GPS metadata, the algorithm might distribute your post randomly (e.g., 20% USA, 20% India, 40% China, 20% UK). With location-specific metadata, the algorithm focuses on your target audience. For example, you can ensure your content reaches English-speaking or wealthy regions, improving engagement and relevance.</span></blockquote>\n\n<blockquote expandable><b>2. Bypass AI re-upload detection 🤖</b>\n\n<span class="tg-spoiler">Platforms use AI to detect re-uploaded content, but they start with metadata checks because it’s the fastest and cheapest method. Advanced image recognition requires significant computational resources, so if your metadata mimics genuine iPhone uploads, your content is far less likely to be flagged. Instead, it often gets overlooked, allowing it to bypass these checks. By adding convincing metadata, the platform is more likely to assume you’re the original creator and push your content further.</span></blockquote>\n\n<blockquote expandable><b>3. Algorithms favor authentic content ✅</b>\n\n<span class="tg-spoiler">Platforms prioritize content they perceive as genuine. Photos or videos with iPhone-like metadata appear authentic, which makes them more likely to be promoted by the algorithm. Authentic metadata signals to the platform that the content is original and worth pushing to more users.</span></blockquote>\n\n<blockquote expandable><b>4. Lower risk of account bans 🔒</b>\n\n<span class="tg-spoiler">When pushing content aggressively, there’s always a risk of being flagged as spam. Metadata that appears authentic makes your account look like it belongs to a real user rather than a bot. Platforms are less likely to flag or ban accounts with legitimate-looking metadata, giving you a safer way to grow your content reach.</span></blockquote>`,
  setLocation:
    "<b>🗺️ Send a location where you want the content to appear as taken from.</b>\n\nClick the 📎 icon and see 'location' in the bottom bar.\n\n<blockquote expandable><b>How adding location helps?</b>\n\n1. Posts are more likely to be pushed to people in that location.  You can target high income countries like USA, UAE etc.\n\n2. Your account is less likely to get banned as it's assumed you're posting raw content taken on an iPhone - not copied, AI etc. This gives your account more trust in the algorithm and it will be less likely to be flagged.</blockquote>",
  register:
    "We don't have you on the system yet. Please register by sending a location that you want your photos to appear as taken from.  Send a location by clicking the 📎 icon and selecting 'location' in the bottom bar.",
  pay: "Ah it looks like you don't have a subscription. Either subscribe for <b>unlimited requests</b> or pay for a <b>single request</b>.",
};

export default messages;
